name: Deploy to ECS

on:
  workflow_call:
    inputs:
      aws-region:
        description: AWS region
        type: string
        default: eu-central-1
      environment:
        description: Github environment to deploy to
        type: string
      task-definition-path:
        description: Path to ECS task definition json file
        type: string
      ecs-cluster-name:
        description: ECS cluster name
        type: string
      ecs-service-name:
        decscription: ECS servcice name
        type: string
    secrets:
      OIDC_ROLE_ARN:
        required: true

concurrency:
  group: ${{ github.ref }}

permissions:
  id-token: write
  contents: read

jobs:
  deploy-ecs:
    needs:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ inputs.aws-region }}
          role-session-name: github-oidc-role
          role-to-assume: ${{ secrets.OIDC_ROLE_ARN }}

      - name: App Settings Variable Substitution
        uses: microsoft/variable-substitution@v1
        with:
          files: ${{ inputs.task-definition-path }}
        env:
          containerDefinitions.0.image: 236013710825.dkr.ecr.eu-central-1.amazonaws.com/services/tangem/tangem-bot-ai:v1.0.0
          volumes.0.efsVolumeConfiguration.fileSystemId: fs-061a4049c301d83aa

      - name: Print task definition
        run: cat ${{ inputs.task-definition-path }}

      - name: Deploy to Amazon ECS
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: deployment/ecs-task-definition.json
          service: ${{ inputs.ecs-service-name }}
          cluster: ${{ inputs.ecs-cluster-name }}
          wait-for-service-stability: true