name: Build

on:
  workflow_call:
    inputs:
      #slack notification
      channel:
        required: true
        type: string
      message_ts:
        required: false
        type: string
      title:
        required: true
        type: string
      #Alpha, Beta, Rc  
      stage: 
        required: true
        type: string
      version:
        required: true
        type: string
      build_number:
        required: true
        type: string
      changelog:
        required: false
        type: string
    
    secrets:
      SLACK_BOT_TOKEN:
        required: true
      GH_MOBILE_PAT:
        required: true

    outputs:
      ts:
        description: "Slack message ts"
        value: ${{ jobs.slack_notification.outputs.ts }}

env:
  app_path: "fastlane/builds/app.ipa"
  artifact_name: Tangem App

jobs:
  build:
    name: Build
    outputs:
      ts: ${{ steps.slack_message.outputs.ts }}
    runs-on: self-hosted
    steps:
    - name: Start building Slack message
      id: slack_notification
      uses: slackapi/slack-github-action@v1.23.0
      with:
       channel-id: "${{ inputs.channel }}"
       update-ts: "${{ inputs.message_ts }}"
       payload: |
        {
            "text": "${{ title }}",
            "blocks": [
                {
                    "type": "header",
                    "text": {
                        "type": "plain_text",
                        "text": "${{ title }}",
                        "emoji": true
                    }
                },
                {
                    "type": "context",
                    "elements": [
                        {
                            "type": "mrkdwn",
                            "text": "🕑 *Building…*"
                        }
                    ]
                },
                {
                    "type": "section",
                    "fields": [
                        {
                            "type": "mrkdwn",
                            "text": "*Version:*\n${{ inputs.version }}"
                        },
                        {
                            "type": "mrkdwn",
                            "text": "*Build number:*\n${{ inputs.build_number }}"
                        }
                    ]
                },
                {
                    "type": "section",
                    "fields": [
                        {
                            "type": "mrkdwn",
                            "text": "*Branch:*\n${{ github.ref_name }}"
                        },
                        {
                            "type": "mrkdwn",
                            "text": "*Started by:*\n${{ github.actor }}"
                        }
                    ]
                },
                {
                    "type": "section",
                    "text": {
                        "type": "mrkdwn",
                        "text": "*Changelog:*\n${{ inputs.changelog }}"
                    }
                },
                {
                    "type": "section",
                    "text": {
                        "type": "mrkdwn",
                        "text": "<${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|View this action on GitHub>"
                    }
                }
            ]
        }
      env:
       SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN}}
       
    - name: Clean
      run: rm -rf *

    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: true
        token: ${{ secrets.GH_MOBILE_PAT }}

    - name: Bundle install
      run: bundle install --jobs 4 --retry 3

    - name: Build
      run: bundle exec fastlane alpha build:"${{ inputs.build_number }}" version:"${{ inputs.version }}"

    - name: Upload binary artifact
      uses: actions/upload-artifact@v3
      with:
        name: ${{ env.artifact_name }}
        path: ${{ env.app_path }}
        if-no-files-found: error
