name: Build Docker image

on:
  workflow_call:
    inputs:
      docker-repository:
        description: Docker registry repository name
        type: string
        required: true
      release-version:
        description: Semantic Version release
        type: string
        required: true
      aws-region:
        description: AWS region
        type: string
        default: eu-central-1
    secrets:
      OIDC_ROLE_ARN:
        required: true
    outputs:
      image:
        description: Full AWS ECR image
        value: ${{ jobs.login-ecr.outputs.registry}}/${{ inputs.docker-repository }}

concurrency:
  group: ${{ github.ref }}

permissions:
  id-token: write
  contents: read

jobs:
  build:
    name: Build docker image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ inputs.aws-region }}
          role-session-name: github-oidc-role
          role-to-assume: ${{ secrets.OIDC_ROLE_ARN }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Build and push
        id: build-image
        uses: docker/build-push-action@v6
        with:
          platforms: linux/arm64,linux/amd64
          context: .
          push: true
          tags: |
            ${{ steps.login-ecr.outputs.registry }}/${{ inputs.docker-repository }}:${{ inputs.release-version }}
          build-args: |
            AppVersion=${{ inputs.release-version }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          github-token: ${{ secrets.GITHUB_TOKEN }}