name: Deploy

on:
  workflow_call:
    inputs:
      #slack notification
      channel:
        required: true
        type: string
      message_ts:
        required: false
        type: string
      title:
        required: true
        type: string
      #alpha, beta, rc  
      stage: 
        required: true
        type: string
      version:
        required: true
        type: string
      build_number:
        required: true
        type: string
      changelog:
        required: false
        type: string
      app_name: 
        required: false
        type: string
    
    secrets:
      SLACK_BOT_TOKEN:
        required: true
      FIREBASE_APP_ID:
        required: true
      FIREBASE_CLI_TOKEN:
        required: true

    outputs:
      ts:
        description: "Slack message ts"
        value: ${{ jobs.deploy.outputs.ts }}

env:
  app_path: "fastlane/builds/app.ipa"
  artifact_name: Tangem App

jobs:
  deploy:
    name: Deploy
    outputs:
      ts: ${{ steps.slack_notification.outputs.ts }}
    runs-on: self-hosted
    environment: ${{ inputs.stage }}
    steps:
    - name: Start building Slack message
      id: slack_notification
      uses: slackapi/slack-github-action@v1.23.0
      with:
       channel-id: "${{ inputs.channel }}"
       update-ts: "${{ inputs.message_ts }}"
       payload: |
        {
            "text": "${{ inputs.title }}",
            "blocks": [
                {
                    "type": "header",
                    "text": {
                        "type": "plain_text",
                        "text": "${{ inputs.title }}",
                        "emoji": true
                    }
                },
                {
                    "type": "context",
                    "elements": [
                        {
                            "type": "mrkdwn",
                            "text": "🕞 *Deploying…*"
                        }
                    ]
                },
                {
                    "type": "section",
                    "fields": [
                        {
                            "type": "mrkdwn",
                            "text": "*Version:*\n${{ inputs.version }}"
                        },
                        {
                            "type": "mrkdwn",
                            "text": "*Build number:*\n${{ inputs.build_number }}"
                        }
                    ]
                },
                {
                    "type": "section",
                    "fields": [
                        {
                            "type": "mrkdwn",
                            "text": "*Branch:*\n${{ github.ref_name }}"
                        },
                        {
                            "type": "mrkdwn",
                            "text": "*Started by:*\n${{ github.actor }}"
                        }
                    ]
                },
                {
                    "type": "section",
                    "text": {
                        "type": "mrkdwn",
                        "text": "*Changelog:*\n${{ inputs.changelog }}"
                    }
                },
                {
                    "type": "section",
                    "text": {
                        "type": "mrkdwn",
                        "text": "<${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|View this action on GitHub>"
                    }
                }
            ]
        }
      env:
       SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN}}
       
    - name: Download the artifact
      uses: actions/download-artifact@v3
      with:
        name: ${{ inputs.app_name }}
        path: artifacts/
       
    - name: Deploy to Firebase
      run: bundle exec fastlane deploy_to_firebase app_id:"${{ secrets.FIREBASE_APP_ID }}" path:"artifacts/${{ inputs.app_name }}" firebase_token:"${{ secrets.FIREBASE_CLI_TOKEN }}" changelog:"${{inputs.changelog}}" 
