name: Firebase

on:
  workflow_call:
    inputs:
      # Stage will be passed to Fastlane to prepare the right build and sign it with the right certificate
      # Alpha - Alpha build, aka Feature build, is built from a feature branch and will be deployed to Google Distribution
      # Beta - Alpha build, aka Development build, is built from a develop branch and will be deployed to Google Distribution
      # RC - RC build is built from the release branch and will be deployed to the application stores
      stage:
        required: true
        type: string
      # Version will be set to the app and will be shown in Google distribution, application store as well as inside the app.
      # Versions can be either semantic (like 1.2.0) or Jira task key (IOS-123)
      version:
        required: true
        type: string
      # Buld number must be unique and incremented every run
      build_number:
        required: true
        type: string
      # (Optional) List of changes that will be shown in App Distribution or application store
      changelog:
        required: false
        type: string
      # (Optional) Additional info about the build
      build_description:
        required: false
        type: string
      # Name that will be used for the artifact
      filename:
        required: true
        type: string

    outputs:
      encoded_release_url:
        description: "Encoded Firebase URL for the uploaded release"
        value: ${{ jobs.deploy.outputs.encoded_release_url }}

    secrets:
      FIREBASE_APP_ID:
        required: true
      FIREBASE_CLI_TOKEN:
        required: true
      # Token must have read access to all the submodule repositories
      GH_MOBILE_PAT:
        required: true

jobs:
  deploy:
    name: Deploy
    runs-on: [self-hosted, active]
    environment: ${{ inputs.stage }}
    outputs:
      encoded_release_url: ${{ env.encoded_release_url }}
    steps:
    # Clean build folder. Since this job runs on a self-hosted runner build folder has to be cleaned manually.
    - name: Clean
      run: rm -rf *

    # Check out git repositories and submodules to get fatslane instructions
    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: true
        token: ${{ secrets.GH_MOBILE_PAT }}

    - name: Install required dependencies
      run: ./bootstrap.sh

    - name: Download the artifact
      uses: actions/download-artifact@v4
      with:
        name: ${{ inputs.filename }}
        path: artifacts/

    - name: Deploy to Firebase
      env:
        RAW_CHANGELOG: '${{ inputs.changelog }}'
        BUILD_DESCRIPTION: '${{ inputs.build_description }}'
      run: |
        # Changelog is prepared here inline instead of a separate step due to
        # an issue with passing multi-line strings between GA steps

        # Fallback if there is no changelog info; e.g. when there is no Jira task associated with the branch
        if [[ "${RAW_CHANGELOG}" =~ ^[[:space:]]*$ || "${RAW_CHANGELOG}" == "false" ]]; then
          RAW_CHANGELOG="N/A"
        fi

        if [[ -n "${BUILD_DESCRIPTION}" ]]; then
        # Workaround for handling a multi-line text with control characters in Bash
        # The lack of indentation within the `if-fi` scope is intentional, do not fix it
        CHANGELOG+=$(cat <<EOF
        Description: ${BUILD_DESCRIPTION}
        EOF
        )$'\n'
        fi

        if [ "$(echo "$RAW_CHANGELOG" | wc -l)" -gt 1 ]; then
        # Workaround for handling a multi-line text with control characters in Bash
        # The lack of indentation within the `if-fi` scope is intentional, do not fix it
        CHANGELOG+=$(cat <<EOF
        Changelog:
        ${RAW_CHANGELOG}
        EOF
        )
        else
          CHANGELOG+="Changelog: ${RAW_CHANGELOG}"
        fi

        # The initialization of rbenv is required before every `bundle` call since Gihub Actions spawns each 'run' step in a separate process
        eval "$(rbenv init - bash)"

        bundle exec fastlane \
        deploy_firebase \
        app_id:"${{ secrets.FIREBASE_APP_ID }}" \
        path:"artifacts/${{ inputs.filename }}" \
        firebase_token:"${{ secrets.FIREBASE_CLI_TOKEN }}" \
        changelog:"${CHANGELOG}"
