name: Slack build and delpoy notification

on:
  workflow_call:
    inputs:
      channel:
        required: true
        type: string
      message_ts:
        required: false
        type: string
      status:
        required: true
        type: string
      app_name:
        required: true
        type: string
      deploy_to:
        required: true
        type: string
      version:
        required: true
        type: string
      build_number:
        required: true
        type: string
      changelog:
        required: false
        type: string
    secrets:
      SLACK_BOT_TOKEN:
        required: true

    outputs:
      ts:
        description: "Slack message ts"
        value: ${{ jobs.slack_notification.outputs.ts }}

jobs:
  slack_notification:
    name: Slack
    outputs:
      ts: ${{ steps.slack_message.outputs.ts }}
    runs-on: ubuntu-latest
    steps:
    - name: Prepare statuses
      id: statuses
      run: |
        if ${{ inputs.status == 'building' }}; then
          echo "status=🕑 *Building…*" >> $GITHUB_OUTPUT
          echo "color=null" >> $GITHUB_OUTPUT
        elif ${{ inputs.status == 'deploying' }}; then
          echo "status=🕞 *Deploying…*" >> $GITHUB_OUTPUT
          echo "color=null" >> $GITHUB_OUTPUT
        elif ${{ inputs.status == 'success' }}; then
          echo "status=🟢 *Built and deployed*" >> $GITHUB_OUTPUT
          echo "color=green" >> $GITHUB_OUTPUT
        elif ${{ inputs.status == 'error' }}; then
          echo "status=🔴 *Error occured*" >> $GITHUB_OUTPUT
          echo "color=red" >> $GITHUB_OUTPUT
        fi

    - name: Prepare changelog
      id: changelog
      run: |
        CHANGELOG=${{ inputs.changelog }}
        CHANGELOG="${CHANGELOG//'%'/'%25'}"
        CHANGELOG="${CHANGELOG//$'\n'/'%0A'}"
        CHANGELOG="${CHANGELOG//$'\r'/'%0D'}"
        echo "text=$CHANGELOG" >> $GITHUB_OUTPUT
        
    - id: slack_message
      uses: slackapi/slack-github-action@v1.23.0
      with:
       channel-id: "${{ inputs.channel }}"
       update-ts: "${{ inputs.message_ts }}"
       payload: |
        {
            "text": "${{ inputs.app_name }} → ${{ inputs.deploy_to }}",
            "blocks": [
                {
                    "type": "header",
                    "text": {
                        "type": "plain_text",
                        "text": "${{ inputs.app_name }} → ${{ inputs.deploy_to }}",
                        "emoji": true
                    }
                },
                {
                    "type": "context",
                    "elements": [
                        {
                            "type": "mrkdwn",
                            "text": "${{ steps.statuses.outputs.status }}"
                        }
                    ]
                },
                {
                    "type": "section",
                    "fields": [
                        {
                            "type": "mrkdwn",
                            "text": "*Version:*\n${{ inputs.version }}"
                        },
                        {
                            "type": "mrkdwn",
                            "text": "*Build number:*\n${{ inputs.build_number }}"
                        },
                        {
                            "type": "mrkdwn",
                            "text": "*Commmit:*\n${{ github.sha }}"
                        }
                    ]
                },
                {
                    "type": "section",
                    "fields": [
                        {
                            "type": "mrkdwn",
                            "text": "*Branch:*\n${{ github.ref_name }}"
                        },
                        {
                            "type": "mrkdwn",
                            "text": "*Started by:*\n${{ github.actor }}"
                        }
                    ]
                },
                {
                    "type": "section",
                    "text": {
                        "type": "mrkdwn",
                        "text": "*Changelog:*\n${{ steps.changelog.outputs.text }}"
                    }
                },
                {
                    "type": "section",
                    "text": {
                        "type": "mrkdwn",
                        "text": "<${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|View this action on GitHub>"
                    }
                }
            ]
        }
      env:
       SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN}}
