name: Prepare Release
# This action creates 
on:
  workflow_call:
    inputs:
      versionName:
        required: true
        type: string
      releaseType:
        required: true
        type: string
    secrets:
      GH_MOBILE_PAT:
        required: true
      JIRA_BASE_URL:
        required: true
      JIRA_USER_EMAIL:
        required: true
      JIRA_API_TOKEN:
        required: true
        
jobs:
  prepare:
    name: Create release branch
    runs-on: ubuntu-latest
    outputs:
      changelog: ${{ steps.changelog.outputs.result }}
      version: ${{ steps.jira.outputs.key }}
      stage: "RC"
      build_number: ${{ github.run_number }}
    steps:
    - name: Create release branch
      uses: actions/github-script@v4
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
          github.git.createRef({
            context.repo.owner,
            context.repo.repo,
            "refs/heads/${{ inputs.releaseType }}/${{ inputs.versionName }}",
            ${{ github.sha }},
          });

    - name: Get unreleased tasks
      id: git-diff
      uses: tangem/github-action@main
      with:
        github-token: ${{ secrets.GH_MOBILE_PAT}}
        base: "master"
        head: "${{ inputs.releaseType }}/${{ inputs.versionName }}"

    - name: Jira Login
      uses: atlassian/gajira-login@master
      env:
        JIRA_BASE_URL: ${{ secrets.JIRA_URL }}
        JIRA_USER_EMAIL: ${{ secrets.JIRA_USER }}
        JIRA_API_TOKEN: ${{ secrets.JIRA_TOKEN }}
      
    - name: Jira Get Issues Summary
      uses: tangem/jira-action@master
      id: changelog
      with:
        action: getIssuesSummary
        issues: ${{ steps.git-diff.outputs.issues }}

    - name: Jira Set Version To Issues
      uses: tangem/jira-action@master
      with:
       action: setVersionToIssues
       project: IOS
       version: ${{ inputs.versionName }}
       issues: ${{ steps.git-diff.outputs.issues }}
  
    - name: Create Pull request to master
      uses: actions/github-script@v4
      with:
        github-token: ${{secrets.GH_MOBILE_PAT}}
        script: |
          github.pulls.create({
            owner: context.repo.owner,
            repo: context.repo.repo,
            head: "${{ inputs.releaseType }}/${{ inputs.versionName }}",
            base: "master",
            title: "▶️ Release version ${{ github.event.inputs.versionName }}",
          });
