name: Prepare Release

on:
  workflow_call:
    inputs:
      versionName:
        required: true
        type: string
      releaseType:
        required: true
        type: string
    secrets:
      GH_MOBILE_PAT:
        required: true
      JIRA_BASE_URL:
        required: true
      JIRA_USER_EMAIL:
        required: true
      JIRA_API_TOKEN:
        required: true

jobs:
  prepare:
    name: Create release branch
    runs-on: ubuntu-latest
    outputs:
      changelog: ${{ steps.changelog.outputs.result }}
      version: ${{ steps.jira.outputs.key }}
      stage: "RC"
      build_number: ${{ github.run_number }}  # TODO: Fetch actual build number
    steps:
    - name: Create release branch
      uses: actions/github-script@v7
      with:
        github-token: ${{ secrets.GH_MOBILE_PAT }}
        script: |
          await github.rest.git.createRef({
            owner: context.repo.owner,
            repo: context.repo.repo,
            ref: "refs/heads/releases/${{ inputs.versionName }}",
            sha: context.sha
          })

    - name: Jira Login
      uses: atlassian/gajira-login@master
      if: ${{ inputs.releaseType == 'release' }}
      env:
        JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
        JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
        JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}

    - name: Jira Rename Version
      uses: tangem/jira-action@master
      if: ${{ inputs.releaseType == 'release' }}
      with:
       action: renameVersion
       project: IOS
       version: "Next Release"
       new-name: ${{ inputs.versionName }}
  
    - name: Create Pull request to master
      uses: actions/github-script@v4
      if: false # TODO: Remove if not used
      with:
        github-token: ${{secrets.GH_MOBILE_PAT}}
        script: |
          github.pulls.create({
            owner: context.repo.owner,
            repo: context.repo.repo,
            head: "${{ inputs.releaseType }}/${{ inputs.versionName }}",
            base: "master",
            title: "▶️ Release version ${{ github.event.inputs.versionName }}",
          });
