name: Slack build and delpoy notification

on:
  workflow_call:
    inputs:
      channel:
        required: true
        type: string
      message_ts:
        required: false
        type: string
      status:
        required: true
        type: string
      app_name:
        required: true
        type: string
      deploy_to:
        required: true
        type: string
      version:
        required: true
        type: string
      build_number:
        required: true
        type: string
      changelog:
        required: false
        type: string
    secrets:
      SLACK_BOT_TOKEN:
        required: true

    outputs:
      ts:
        description: "Slack message ts"
        value: ${{ jobs.slack_notification.outputs.ts }}

jobs:
  slack_notification:
    name: Slack
    outputs:
      ts: ${{ steps.slack_message.outputs.ts }}
    runs-on: ubuntu-latest
    steps:
    - name: Prepare statuses
      id: statuses
      run: |
        if ${{ inputs.status == 'building' }}; then
          echo "status=🕑 *Building…*" >> $GITHUB_OUTPUT
          echo "color=null" >> $GITHUB_OUTPUT
        elif ${{ inputs.status == 'deploying' }}; then
          echo "status=🕞 *Deploying…*" >> $GITHUB_OUTPUT
          echo "color=null" >> $GITHUB_OUTPUT
        elif ${{ inputs.status == 'success' }}; then
          echo "status=🟢 *Built and deployed*" >> $GITHUB_OUTPUT
          echo "color=green" >> $GITHUB_OUTPUT
        elif ${{ inputs.status == 'error' }}; then
          echo "status=🔴 *Error occured*" >> $GITHUB_OUTPUT
          echo "color=red" >> $GITHUB_OUTPUT
        fi
        
    - id: slack_message
      uses: slackapi/slack-github-action@v1.23.0
      with:
       channel-id: "${{ inputs.channel }}"
       update-ts: "${{ inputs.message_ts }}"
       payload: ${{ vars.SLACK_JSON }}
      env:
       SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN}}
